// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oDN5G7CnsSoNxUeRZw_b0uDeJKkDlAw',
    appId: '1:847890425963:web:87c7450ce47ec87610692e',
    messagingSenderId: '847890425963',
    projectId: 'project-avalon-703cf',
    authDomain: 'project-avalon-703cf.firebaseapp.com',
    storageBucket: 'project-avalon-703cf.appspot.com',
    measurementId: 'G-48L1H4CLKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMgx6f4cvoxwhSOPFFXGO6vu6OIbH03DQ',
    appId: '1:847890425963:android:7a8ce5ae175c47eb10692e',
    messagingSenderId: '847890425963',
    projectId: 'project-avalon-703cf',
    storageBucket: 'project-avalon-703cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOuTzcL9XWXOFRsfAmPTjjgKrS2Idj0U',
    appId: '1:847890425963:ios:a63d3f006c5b4a9f10692e',
    messagingSenderId: '847890425963',
    projectId: 'project-avalon-703cf',
    storageBucket: 'project-avalon-703cf.appspot.com',
    iosBundleId: 'com.example.avalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOuTzcL9XWXOFRsfAmPTjjgKrS2Idj0U',
    appId: '1:847890425963:ios:a63d3f006c5b4a9f10692e',
    messagingSenderId: '847890425963',
    projectId: 'project-avalon-703cf',
    storageBucket: 'project-avalon-703cf.appspot.com',
    iosBundleId: 'com.example.avalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7oDN5G7CnsSoNxUeRZw_b0uDeJKkDlAw',
    appId: '1:847890425963:web:318735ca36856d1c10692e',
    messagingSenderId: '847890425963',
    projectId: 'project-avalon-703cf',
    authDomain: 'project-avalon-703cf.firebaseapp.com',
    storageBucket: 'project-avalon-703cf.appspot.com',
    measurementId: 'G-FWZRK6JN0P',
  );
}
